import { faMoneyBillTransfer, faChartPie } from '@fortawesome/free-solid-svg-icons'
import { CardItemDto } from '../dtos/card-item.dto'

export class DefichainRepository {
  static all(): CardItemDto[] {
    return [realYield, portfolioTracker]
  }
}

const realYield: CardItemDto = {
  name: 'Real yield',
  description: 'A display of real yield generated by defichain',
  icon: { definition: faMoneyBillTransfer, color: '#666', size: '4x' },
  links: [{ url: '/defichain/real-yield', display: 'Open statistics' }],
}

const portfolioTracker: CardItemDto = {
  name: 'Portfolio tracker',
  description: 'Start tracking your addresses and receive different insights and a development history',
  icon: { definition: faChartPie, color: '#666', size: '4x' },
  links: [{ url: '/defichain/portfolio-tracker', display: 'Open tracker' }],
}
